version: 1
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    working_directory: ~/app

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - app-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: app-{{ checksum "pom.xml" }}

      - run:
          name: Packaging
          command : mvn clean package

      -  run:
           name: Say Hello
           command :  echo "Hello World"

      - run:
          name: Setting up Docker
          command: |
            echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Push app to DockerHub
          command: |
            docker build --tag=aliyura/week11:latest .
            docker push aliyura/week11:latest
